version: "3.7"
services:
    notebook:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
           - "8888:8888"
        volumes:
           - "./src:/home/jovyan/work" 
        command: start-notebook.sh --NotebookApp.token=''
    app:
      container_name: app
      build: 
        context: .
        dockerfile: dev.Dockerfile
      volumes:
      - ./src:/src
      tty: true